/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { DROPSY_AIRDROP_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CLAIM_AIRDROP_DISCRIMINATOR = new Uint8Array([
  137, 50, 122, 111, 89, 254, 8, 20,
]);

export function getClaimAirdropDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_AIRDROP_DISCRIMINATOR,
  );
}

export type ClaimAirdropInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountSourceTokenAccount extends string | AccountMeta<string> = string,
  TAccountDestinationTokenAccount extends string | AccountMeta<string> = string,
  TAccountClaimer extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> =
    "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountAirdropConfig extends string | AccountMeta<string> = string,
  TAccountProtocolTreasury extends string | AccountMeta<string> = string,
  TAccountAirdropMaster extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountMasterCreator extends string | AccountMeta<string> = string,
  TAccountAirdrop extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountBitmap extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSourceTokenAccount extends string
        ? WritableAccount<TAccountSourceTokenAccount>
        : TAccountSourceTokenAccount,
      TAccountDestinationTokenAccount extends string
        ? WritableAccount<TAccountDestinationTokenAccount>
        : TAccountDestinationTokenAccount,
      TAccountClaimer extends string
        ? WritableSignerAccount<TAccountClaimer> &
            AccountSignerMeta<TAccountClaimer>
        : TAccountClaimer,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountAirdropConfig extends string
        ? ReadonlyAccount<TAccountAirdropConfig>
        : TAccountAirdropConfig,
      TAccountProtocolTreasury extends string
        ? WritableAccount<TAccountProtocolTreasury>
        : TAccountProtocolTreasury,
      TAccountAirdropMaster extends string
        ? ReadonlyAccount<TAccountAirdropMaster>
        : TAccountAirdropMaster,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountMasterCreator extends string
        ? ReadonlyAccount<TAccountMasterCreator>
        : TAccountMasterCreator,
      TAccountAirdrop extends string
        ? WritableAccount<TAccountAirdrop>
        : TAccountAirdrop,
      TAccountAuthority extends string
        ? ReadonlyAccount<TAccountAuthority>
        : TAccountAuthority,
      TAccountBitmap extends string
        ? WritableAccount<TAccountBitmap>
        : TAccountBitmap,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimAirdropInstructionData = {
  discriminator: ReadonlyUint8Array;
  index: bigint;
  proof: Array<ReadonlyUint8Array>;
  amount: bigint;
  claimMapIndex: number;
  airdropId: bigint;
};

export type ClaimAirdropInstructionDataArgs = {
  index: number | bigint;
  proof: Array<ReadonlyUint8Array>;
  amount: number | bigint;
  claimMapIndex: number;
  airdropId: number | bigint;
};

export function getClaimAirdropInstructionDataEncoder(): Encoder<ClaimAirdropInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["index", getU64Encoder()],
      ["proof", getArrayEncoder(fixEncoderSize(getBytesEncoder(), 32))],
      ["amount", getU64Encoder()],
      ["claimMapIndex", getU16Encoder()],
      ["airdropId", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CLAIM_AIRDROP_DISCRIMINATOR }),
  );
}

export function getClaimAirdropInstructionDataDecoder(): Decoder<ClaimAirdropInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["index", getU64Decoder()],
    ["proof", getArrayDecoder(fixDecoderSize(getBytesDecoder(), 32))],
    ["amount", getU64Decoder()],
    ["claimMapIndex", getU16Decoder()],
    ["airdropId", getU64Decoder()],
  ]);
}

export function getClaimAirdropInstructionDataCodec(): Codec<
  ClaimAirdropInstructionDataArgs,
  ClaimAirdropInstructionData
> {
  return combineCodec(
    getClaimAirdropInstructionDataEncoder(),
    getClaimAirdropInstructionDataDecoder(),
  );
}

export type ClaimAirdropAsyncInput<
  TAccountSourceTokenAccount extends string = string,
  TAccountDestinationTokenAccount extends string = string,
  TAccountClaimer extends string = string,
  TAccountMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountAirdropConfig extends string = string,
  TAccountProtocolTreasury extends string = string,
  TAccountAirdropMaster extends string = string,
  TAccountTreasury extends string = string,
  TAccountMasterCreator extends string = string,
  TAccountAirdrop extends string = string,
  TAccountAuthority extends string = string,
  TAccountBitmap extends string = string,
> = {
  sourceTokenAccount: Address<TAccountSourceTokenAccount>;
  destinationTokenAccount?: Address<TAccountDestinationTokenAccount>;
  claimer: TransactionSigner<TAccountClaimer>;
  mint: Address<TAccountMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  airdropConfig?: Address<TAccountAirdropConfig>;
  protocolTreasury: Address<TAccountProtocolTreasury>;
  airdropMaster?: Address<TAccountAirdropMaster>;
  treasury: Address<TAccountTreasury>;
  masterCreator: Address<TAccountMasterCreator>;
  airdrop: Address<TAccountAirdrop>;
  authority: Address<TAccountAuthority>;
  bitmap: Address<TAccountBitmap>;
  index: ClaimAirdropInstructionDataArgs["index"];
  proof: ClaimAirdropInstructionDataArgs["proof"];
  amount: ClaimAirdropInstructionDataArgs["amount"];
  claimMapIndex: ClaimAirdropInstructionDataArgs["claimMapIndex"];
  airdropId: ClaimAirdropInstructionDataArgs["airdropId"];
};

export async function getClaimAirdropInstructionAsync<
  TAccountSourceTokenAccount extends string,
  TAccountDestinationTokenAccount extends string,
  TAccountClaimer extends string,
  TAccountMint extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TAccountAirdropConfig extends string,
  TAccountProtocolTreasury extends string,
  TAccountAirdropMaster extends string,
  TAccountTreasury extends string,
  TAccountMasterCreator extends string,
  TAccountAirdrop extends string,
  TAccountAuthority extends string,
  TAccountBitmap extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: ClaimAirdropAsyncInput<
    TAccountSourceTokenAccount,
    TAccountDestinationTokenAccount,
    TAccountClaimer,
    TAccountMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountAirdrop,
    TAccountAuthority,
    TAccountBitmap
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ClaimAirdropInstruction<
    TProgramAddress,
    TAccountSourceTokenAccount,
    TAccountDestinationTokenAccount,
    TAccountClaimer,
    TAccountMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountAirdrop,
    TAccountAuthority,
    TAccountBitmap
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    sourceTokenAccount: {
      value: input.sourceTokenAccount ?? null,
      isWritable: true,
    },
    destinationTokenAccount: {
      value: input.destinationTokenAccount ?? null,
      isWritable: true,
    },
    claimer: { value: input.claimer ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    airdropConfig: { value: input.airdropConfig ?? null, isWritable: false },
    protocolTreasury: {
      value: input.protocolTreasury ?? null,
      isWritable: true,
    },
    airdropMaster: { value: input.airdropMaster ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: true },
    masterCreator: { value: input.masterCreator ?? null, isWritable: false },
    airdrop: { value: input.airdrop ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    bitmap: { value: input.bitmap ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.destinationTokenAccount.value) {
    accounts.destinationTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.claimer.value)),
        getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.airdropConfig.value) {
    accounts.airdropConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 105, 114, 100, 114, 111, 112, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.airdropMaster.value) {
    accounts.airdropMaster.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 105, 114, 100, 114, 111, 112, 95, 109, 97, 115, 116, 101, 114,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.masterCreator.value)),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.sourceTokenAccount),
      getAccountMeta(accounts.destinationTokenAccount),
      getAccountMeta(accounts.claimer),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.airdropConfig),
      getAccountMeta(accounts.protocolTreasury),
      getAccountMeta(accounts.airdropMaster),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.masterCreator),
      getAccountMeta(accounts.airdrop),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.bitmap),
    ],
    data: getClaimAirdropInstructionDataEncoder().encode(
      args as ClaimAirdropInstructionDataArgs,
    ),
    programAddress,
  } as ClaimAirdropInstruction<
    TProgramAddress,
    TAccountSourceTokenAccount,
    TAccountDestinationTokenAccount,
    TAccountClaimer,
    TAccountMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountAirdrop,
    TAccountAuthority,
    TAccountBitmap
  >);
}

export type ClaimAirdropInput<
  TAccountSourceTokenAccount extends string = string,
  TAccountDestinationTokenAccount extends string = string,
  TAccountClaimer extends string = string,
  TAccountMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountAirdropConfig extends string = string,
  TAccountProtocolTreasury extends string = string,
  TAccountAirdropMaster extends string = string,
  TAccountTreasury extends string = string,
  TAccountMasterCreator extends string = string,
  TAccountAirdrop extends string = string,
  TAccountAuthority extends string = string,
  TAccountBitmap extends string = string,
> = {
  sourceTokenAccount: Address<TAccountSourceTokenAccount>;
  destinationTokenAccount: Address<TAccountDestinationTokenAccount>;
  claimer: TransactionSigner<TAccountClaimer>;
  mint: Address<TAccountMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  airdropConfig: Address<TAccountAirdropConfig>;
  protocolTreasury: Address<TAccountProtocolTreasury>;
  airdropMaster: Address<TAccountAirdropMaster>;
  treasury: Address<TAccountTreasury>;
  masterCreator: Address<TAccountMasterCreator>;
  airdrop: Address<TAccountAirdrop>;
  authority: Address<TAccountAuthority>;
  bitmap: Address<TAccountBitmap>;
  index: ClaimAirdropInstructionDataArgs["index"];
  proof: ClaimAirdropInstructionDataArgs["proof"];
  amount: ClaimAirdropInstructionDataArgs["amount"];
  claimMapIndex: ClaimAirdropInstructionDataArgs["claimMapIndex"];
  airdropId: ClaimAirdropInstructionDataArgs["airdropId"];
};

export function getClaimAirdropInstruction<
  TAccountSourceTokenAccount extends string,
  TAccountDestinationTokenAccount extends string,
  TAccountClaimer extends string,
  TAccountMint extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TAccountAirdropConfig extends string,
  TAccountProtocolTreasury extends string,
  TAccountAirdropMaster extends string,
  TAccountTreasury extends string,
  TAccountMasterCreator extends string,
  TAccountAirdrop extends string,
  TAccountAuthority extends string,
  TAccountBitmap extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: ClaimAirdropInput<
    TAccountSourceTokenAccount,
    TAccountDestinationTokenAccount,
    TAccountClaimer,
    TAccountMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountAirdrop,
    TAccountAuthority,
    TAccountBitmap
  >,
  config?: { programAddress?: TProgramAddress },
): ClaimAirdropInstruction<
  TProgramAddress,
  TAccountSourceTokenAccount,
  TAccountDestinationTokenAccount,
  TAccountClaimer,
  TAccountMint,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram,
  TAccountAirdropConfig,
  TAccountProtocolTreasury,
  TAccountAirdropMaster,
  TAccountTreasury,
  TAccountMasterCreator,
  TAccountAirdrop,
  TAccountAuthority,
  TAccountBitmap
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    sourceTokenAccount: {
      value: input.sourceTokenAccount ?? null,
      isWritable: true,
    },
    destinationTokenAccount: {
      value: input.destinationTokenAccount ?? null,
      isWritable: true,
    },
    claimer: { value: input.claimer ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    airdropConfig: { value: input.airdropConfig ?? null, isWritable: false },
    protocolTreasury: {
      value: input.protocolTreasury ?? null,
      isWritable: true,
    },
    airdropMaster: { value: input.airdropMaster ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: true },
    masterCreator: { value: input.masterCreator ?? null, isWritable: false },
    airdrop: { value: input.airdrop ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    bitmap: { value: input.bitmap ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.sourceTokenAccount),
      getAccountMeta(accounts.destinationTokenAccount),
      getAccountMeta(accounts.claimer),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.airdropConfig),
      getAccountMeta(accounts.protocolTreasury),
      getAccountMeta(accounts.airdropMaster),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.masterCreator),
      getAccountMeta(accounts.airdrop),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.bitmap),
    ],
    data: getClaimAirdropInstructionDataEncoder().encode(
      args as ClaimAirdropInstructionDataArgs,
    ),
    programAddress,
  } as ClaimAirdropInstruction<
    TProgramAddress,
    TAccountSourceTokenAccount,
    TAccountDestinationTokenAccount,
    TAccountClaimer,
    TAccountMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountAirdrop,
    TAccountAuthority,
    TAccountBitmap
  >);
}

export type ParsedClaimAirdropInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    sourceTokenAccount: TAccountMetas[0];
    destinationTokenAccount: TAccountMetas[1];
    claimer: TAccountMetas[2];
    mint: TAccountMetas[3];
    tokenProgram: TAccountMetas[4];
    associatedTokenProgram: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
    airdropConfig: TAccountMetas[7];
    protocolTreasury: TAccountMetas[8];
    airdropMaster: TAccountMetas[9];
    treasury: TAccountMetas[10];
    masterCreator: TAccountMetas[11];
    airdrop: TAccountMetas[12];
    authority: TAccountMetas[13];
    bitmap: TAccountMetas[14];
  };
  data: ClaimAirdropInstructionData;
};

export function parseClaimAirdropInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClaimAirdropInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 15) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      sourceTokenAccount: getNextAccount(),
      destinationTokenAccount: getNextAccount(),
      claimer: getNextAccount(),
      mint: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
      airdropConfig: getNextAccount(),
      protocolTreasury: getNextAccount(),
      airdropMaster: getNextAccount(),
      treasury: getNextAccount(),
      masterCreator: getNextAccount(),
      airdrop: getNextAccount(),
      authority: getNextAccount(),
      bitmap: getNextAccount(),
    },
    data: getClaimAirdropInstructionDataDecoder().decode(instruction.data),
  };
}
