/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { DROPSY_AIRDROP_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CREATE_BITMAP_DISCRIMINATOR = new Uint8Array([
  69, 92, 61, 190, 154, 237, 116, 247,
]);

export function getCreateBitmapDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_BITMAP_DISCRIMINATOR,
  );
}

export type CreateBitmapInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountAirdropConfig extends string | AccountMeta<string> = string,
  TAccountProtocolTreasury extends string | AccountMeta<string> = string,
  TAccountAirdropMaster extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountMasterCreator extends string | AccountMeta<string> = string,
  TAccountBitmap extends string | AccountMeta<string> = string,
  TAccountAirdrop extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAirdropConfig extends string
        ? ReadonlyAccount<TAccountAirdropConfig>
        : TAccountAirdropConfig,
      TAccountProtocolTreasury extends string
        ? WritableAccount<TAccountProtocolTreasury>
        : TAccountProtocolTreasury,
      TAccountAirdropMaster extends string
        ? ReadonlyAccount<TAccountAirdropMaster>
        : TAccountAirdropMaster,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountMasterCreator extends string
        ? ReadonlyAccount<TAccountMasterCreator>
        : TAccountMasterCreator,
      TAccountBitmap extends string
        ? WritableAccount<TAccountBitmap>
        : TAccountBitmap,
      TAccountAirdrop extends string
        ? WritableAccount<TAccountAirdrop>
        : TAccountAirdrop,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateBitmapInstructionData = {
  discriminator: ReadonlyUint8Array;
  id: number;
  total: number;
  airdropId: bigint;
};

export type CreateBitmapInstructionDataArgs = {
  id: number;
  total: number;
  airdropId: number | bigint;
};

export function getCreateBitmapInstructionDataEncoder(): FixedSizeEncoder<CreateBitmapInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["id", getU16Encoder()],
      ["total", getU32Encoder()],
      ["airdropId", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_BITMAP_DISCRIMINATOR }),
  );
}

export function getCreateBitmapInstructionDataDecoder(): FixedSizeDecoder<CreateBitmapInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["id", getU16Decoder()],
    ["total", getU32Decoder()],
    ["airdropId", getU64Decoder()],
  ]);
}

export function getCreateBitmapInstructionDataCodec(): FixedSizeCodec<
  CreateBitmapInstructionDataArgs,
  CreateBitmapInstructionData
> {
  return combineCodec(
    getCreateBitmapInstructionDataEncoder(),
    getCreateBitmapInstructionDataDecoder(),
  );
}

export type CreateBitmapAsyncInput<
  TAccountAirdropConfig extends string = string,
  TAccountProtocolTreasury extends string = string,
  TAccountAirdropMaster extends string = string,
  TAccountTreasury extends string = string,
  TAccountMasterCreator extends string = string,
  TAccountBitmap extends string = string,
  TAccountAirdrop extends string = string,
  TAccountMint extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  airdropConfig?: Address<TAccountAirdropConfig>;
  protocolTreasury: Address<TAccountProtocolTreasury>;
  airdropMaster?: Address<TAccountAirdropMaster>;
  treasury: Address<TAccountTreasury>;
  masterCreator: Address<TAccountMasterCreator>;
  bitmap?: Address<TAccountBitmap>;
  airdrop?: Address<TAccountAirdrop>;
  mint: Address<TAccountMint>;
  authority: TransactionSigner<TAccountAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: CreateBitmapInstructionDataArgs["id"];
  total: CreateBitmapInstructionDataArgs["total"];
  airdropId: CreateBitmapInstructionDataArgs["airdropId"];
};

export async function getCreateBitmapInstructionAsync<
  TAccountAirdropConfig extends string,
  TAccountProtocolTreasury extends string,
  TAccountAirdropMaster extends string,
  TAccountTreasury extends string,
  TAccountMasterCreator extends string,
  TAccountBitmap extends string,
  TAccountAirdrop extends string,
  TAccountMint extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: CreateBitmapAsyncInput<
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountBitmap,
    TAccountAirdrop,
    TAccountMint,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CreateBitmapInstruction<
    TProgramAddress,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountBitmap,
    TAccountAirdrop,
    TAccountMint,
    TAccountAuthority,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    airdropConfig: { value: input.airdropConfig ?? null, isWritable: false },
    protocolTreasury: {
      value: input.protocolTreasury ?? null,
      isWritable: true,
    },
    airdropMaster: { value: input.airdropMaster ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: true },
    masterCreator: { value: input.masterCreator ?? null, isWritable: false },
    bitmap: { value: input.bitmap ?? null, isWritable: true },
    airdrop: { value: input.airdrop ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.airdropConfig.value) {
    accounts.airdropConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 105, 114, 100, 114, 111, 112, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.airdropMaster.value) {
    accounts.airdropMaster.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 105, 114, 100, 114, 111, 112, 95, 109, 97, 115, 116, 101, 114,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.masterCreator.value)),
      ],
    });
  }
  if (!accounts.airdrop.value) {
    accounts.airdrop.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([97, 105, 114, 100, 114, 111, 112]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.authority.value)),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
        getU64Encoder().encode(expectSome(args.airdropId)),
      ],
    });
  }
  if (!accounts.bitmap.value) {
    accounts.bitmap.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([98, 105, 116, 109, 97, 112])),
        getAddressEncoder().encode(expectAddress(accounts.airdrop.value)),
        getU16Encoder().encode(expectSome(args.id)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.airdropConfig),
      getAccountMeta(accounts.protocolTreasury),
      getAccountMeta(accounts.airdropMaster),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.masterCreator),
      getAccountMeta(accounts.bitmap),
      getAccountMeta(accounts.airdrop),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateBitmapInstructionDataEncoder().encode(
      args as CreateBitmapInstructionDataArgs,
    ),
    programAddress,
  } as CreateBitmapInstruction<
    TProgramAddress,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountBitmap,
    TAccountAirdrop,
    TAccountMint,
    TAccountAuthority,
    TAccountSystemProgram
  >);
}

export type CreateBitmapInput<
  TAccountAirdropConfig extends string = string,
  TAccountProtocolTreasury extends string = string,
  TAccountAirdropMaster extends string = string,
  TAccountTreasury extends string = string,
  TAccountMasterCreator extends string = string,
  TAccountBitmap extends string = string,
  TAccountAirdrop extends string = string,
  TAccountMint extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  airdropConfig: Address<TAccountAirdropConfig>;
  protocolTreasury: Address<TAccountProtocolTreasury>;
  airdropMaster: Address<TAccountAirdropMaster>;
  treasury: Address<TAccountTreasury>;
  masterCreator: Address<TAccountMasterCreator>;
  bitmap: Address<TAccountBitmap>;
  airdrop: Address<TAccountAirdrop>;
  mint: Address<TAccountMint>;
  authority: TransactionSigner<TAccountAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: CreateBitmapInstructionDataArgs["id"];
  total: CreateBitmapInstructionDataArgs["total"];
  airdropId: CreateBitmapInstructionDataArgs["airdropId"];
};

export function getCreateBitmapInstruction<
  TAccountAirdropConfig extends string,
  TAccountProtocolTreasury extends string,
  TAccountAirdropMaster extends string,
  TAccountTreasury extends string,
  TAccountMasterCreator extends string,
  TAccountBitmap extends string,
  TAccountAirdrop extends string,
  TAccountMint extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: CreateBitmapInput<
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountBitmap,
    TAccountAirdrop,
    TAccountMint,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateBitmapInstruction<
  TProgramAddress,
  TAccountAirdropConfig,
  TAccountProtocolTreasury,
  TAccountAirdropMaster,
  TAccountTreasury,
  TAccountMasterCreator,
  TAccountBitmap,
  TAccountAirdrop,
  TAccountMint,
  TAccountAuthority,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    airdropConfig: { value: input.airdropConfig ?? null, isWritable: false },
    protocolTreasury: {
      value: input.protocolTreasury ?? null,
      isWritable: true,
    },
    airdropMaster: { value: input.airdropMaster ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: true },
    masterCreator: { value: input.masterCreator ?? null, isWritable: false },
    bitmap: { value: input.bitmap ?? null, isWritable: true },
    airdrop: { value: input.airdrop ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.airdropConfig),
      getAccountMeta(accounts.protocolTreasury),
      getAccountMeta(accounts.airdropMaster),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.masterCreator),
      getAccountMeta(accounts.bitmap),
      getAccountMeta(accounts.airdrop),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateBitmapInstructionDataEncoder().encode(
      args as CreateBitmapInstructionDataArgs,
    ),
    programAddress,
  } as CreateBitmapInstruction<
    TProgramAddress,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountBitmap,
    TAccountAirdrop,
    TAccountMint,
    TAccountAuthority,
    TAccountSystemProgram
  >);
}

export type ParsedCreateBitmapInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    airdropConfig: TAccountMetas[0];
    protocolTreasury: TAccountMetas[1];
    airdropMaster: TAccountMetas[2];
    treasury: TAccountMetas[3];
    masterCreator: TAccountMetas[4];
    bitmap: TAccountMetas[5];
    airdrop: TAccountMetas[6];
    mint: TAccountMetas[7];
    authority: TAccountMetas[8];
    systemProgram: TAccountMetas[9];
  };
  data: CreateBitmapInstructionData;
};

export function parseCreateBitmapInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateBitmapInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      airdropConfig: getNextAccount(),
      protocolTreasury: getNextAccount(),
      airdropMaster: getNextAccount(),
      treasury: getNextAccount(),
      masterCreator: getNextAccount(),
      bitmap: getNextAccount(),
      airdrop: getNextAccount(),
      mint: getNextAccount(),
      authority: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateBitmapInstructionDataDecoder().decode(instruction.data),
  };
}
