/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getOptionDecoder,
  getOptionEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { DROPSY_AIRDROP_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CREATE_AIRDROP_DISCRIMINATOR = new Uint8Array([
  227, 135, 208, 66, 137, 177, 80, 94,
]);

export function getCreateAirdropDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_AIRDROP_DISCRIMINATOR,
  );
}

export type CreateAirdropInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountAirdropConfig extends string | AccountMeta<string> = string,
  TAccountProtocolTreasury extends string | AccountMeta<string> = string,
  TAccountAirdropMaster extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountMasterCreator extends string | AccountMeta<string> = string,
  TAccountAirdrop extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAirdropConfig extends string
        ? ReadonlyAccount<TAccountAirdropConfig>
        : TAccountAirdropConfig,
      TAccountProtocolTreasury extends string
        ? WritableAccount<TAccountProtocolTreasury>
        : TAccountProtocolTreasury,
      TAccountAirdropMaster extends string
        ? WritableAccount<TAccountAirdropMaster>
        : TAccountAirdropMaster,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountMasterCreator extends string
        ? ReadonlyAccount<TAccountMasterCreator>
        : TAccountMasterCreator,
      TAccountAirdrop extends string
        ? WritableAccount<TAccountAirdrop>
        : TAccountAirdrop,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateAirdropInstructionData = {
  discriminator: ReadonlyUint8Array;
  id: bigint;
  merkleRoot: Option<ReadonlyUint8Array>;
  startsAt: Option<bigint>;
  endsAt: Option<bigint>;
  version: Option<number>;
  delegateAuthority: Option<Address>;
};

export type CreateAirdropInstructionDataArgs = {
  id: number | bigint;
  merkleRoot: OptionOrNullable<ReadonlyUint8Array>;
  startsAt: OptionOrNullable<number | bigint>;
  endsAt: OptionOrNullable<number | bigint>;
  version: OptionOrNullable<number>;
  delegateAuthority: OptionOrNullable<Address>;
};

export function getCreateAirdropInstructionDataEncoder(): Encoder<CreateAirdropInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["id", getU64Encoder()],
      ["merkleRoot", getOptionEncoder(fixEncoderSize(getBytesEncoder(), 32))],
      ["startsAt", getOptionEncoder(getI64Encoder())],
      ["endsAt", getOptionEncoder(getI64Encoder())],
      ["version", getOptionEncoder(getU8Encoder())],
      ["delegateAuthority", getOptionEncoder(getAddressEncoder())],
    ]),
    (value) => ({ ...value, discriminator: CREATE_AIRDROP_DISCRIMINATOR }),
  );
}

export function getCreateAirdropInstructionDataDecoder(): Decoder<CreateAirdropInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["id", getU64Decoder()],
    ["merkleRoot", getOptionDecoder(fixDecoderSize(getBytesDecoder(), 32))],
    ["startsAt", getOptionDecoder(getI64Decoder())],
    ["endsAt", getOptionDecoder(getI64Decoder())],
    ["version", getOptionDecoder(getU8Decoder())],
    ["delegateAuthority", getOptionDecoder(getAddressDecoder())],
  ]);
}

export function getCreateAirdropInstructionDataCodec(): Codec<
  CreateAirdropInstructionDataArgs,
  CreateAirdropInstructionData
> {
  return combineCodec(
    getCreateAirdropInstructionDataEncoder(),
    getCreateAirdropInstructionDataDecoder(),
  );
}

export type CreateAirdropAsyncInput<
  TAccountAirdropConfig extends string = string,
  TAccountProtocolTreasury extends string = string,
  TAccountAirdropMaster extends string = string,
  TAccountTreasury extends string = string,
  TAccountMasterCreator extends string = string,
  TAccountAirdrop extends string = string,
  TAccountMint extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  airdropConfig?: Address<TAccountAirdropConfig>;
  protocolTreasury: Address<TAccountProtocolTreasury>;
  airdropMaster?: Address<TAccountAirdropMaster>;
  treasury: Address<TAccountTreasury>;
  masterCreator: Address<TAccountMasterCreator>;
  airdrop: Address<TAccountAirdrop>;
  mint: Address<TAccountMint>;
  authority: TransactionSigner<TAccountAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: CreateAirdropInstructionDataArgs["id"];
  merkleRoot: CreateAirdropInstructionDataArgs["merkleRoot"];
  startsAt: CreateAirdropInstructionDataArgs["startsAt"];
  endsAt: CreateAirdropInstructionDataArgs["endsAt"];
  version: CreateAirdropInstructionDataArgs["version"];
  delegateAuthority: CreateAirdropInstructionDataArgs["delegateAuthority"];
};

export async function getCreateAirdropInstructionAsync<
  TAccountAirdropConfig extends string,
  TAccountProtocolTreasury extends string,
  TAccountAirdropMaster extends string,
  TAccountTreasury extends string,
  TAccountMasterCreator extends string,
  TAccountAirdrop extends string,
  TAccountMint extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: CreateAirdropAsyncInput<
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountAirdrop,
    TAccountMint,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CreateAirdropInstruction<
    TProgramAddress,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountAirdrop,
    TAccountMint,
    TAccountAuthority,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    airdropConfig: { value: input.airdropConfig ?? null, isWritable: false },
    protocolTreasury: {
      value: input.protocolTreasury ?? null,
      isWritable: true,
    },
    airdropMaster: { value: input.airdropMaster ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    masterCreator: { value: input.masterCreator ?? null, isWritable: false },
    airdrop: { value: input.airdrop ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.airdropConfig.value) {
    accounts.airdropConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 105, 114, 100, 114, 111, 112, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.airdropMaster.value) {
    accounts.airdropMaster.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 105, 114, 100, 114, 111, 112, 95, 109, 97, 115, 116, 101, 114,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.masterCreator.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.airdropConfig),
      getAccountMeta(accounts.protocolTreasury),
      getAccountMeta(accounts.airdropMaster),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.masterCreator),
      getAccountMeta(accounts.airdrop),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateAirdropInstructionDataEncoder().encode(
      args as CreateAirdropInstructionDataArgs,
    ),
    programAddress,
  } as CreateAirdropInstruction<
    TProgramAddress,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountAirdrop,
    TAccountMint,
    TAccountAuthority,
    TAccountSystemProgram
  >);
}

export type CreateAirdropInput<
  TAccountAirdropConfig extends string = string,
  TAccountProtocolTreasury extends string = string,
  TAccountAirdropMaster extends string = string,
  TAccountTreasury extends string = string,
  TAccountMasterCreator extends string = string,
  TAccountAirdrop extends string = string,
  TAccountMint extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  airdropConfig: Address<TAccountAirdropConfig>;
  protocolTreasury: Address<TAccountProtocolTreasury>;
  airdropMaster: Address<TAccountAirdropMaster>;
  treasury: Address<TAccountTreasury>;
  masterCreator: Address<TAccountMasterCreator>;
  airdrop: Address<TAccountAirdrop>;
  mint: Address<TAccountMint>;
  authority: TransactionSigner<TAccountAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: CreateAirdropInstructionDataArgs["id"];
  merkleRoot: CreateAirdropInstructionDataArgs["merkleRoot"];
  startsAt: CreateAirdropInstructionDataArgs["startsAt"];
  endsAt: CreateAirdropInstructionDataArgs["endsAt"];
  version: CreateAirdropInstructionDataArgs["version"];
  delegateAuthority: CreateAirdropInstructionDataArgs["delegateAuthority"];
};

export function getCreateAirdropInstruction<
  TAccountAirdropConfig extends string,
  TAccountProtocolTreasury extends string,
  TAccountAirdropMaster extends string,
  TAccountTreasury extends string,
  TAccountMasterCreator extends string,
  TAccountAirdrop extends string,
  TAccountMint extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: CreateAirdropInput<
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountAirdrop,
    TAccountMint,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateAirdropInstruction<
  TProgramAddress,
  TAccountAirdropConfig,
  TAccountProtocolTreasury,
  TAccountAirdropMaster,
  TAccountTreasury,
  TAccountMasterCreator,
  TAccountAirdrop,
  TAccountMint,
  TAccountAuthority,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    airdropConfig: { value: input.airdropConfig ?? null, isWritable: false },
    protocolTreasury: {
      value: input.protocolTreasury ?? null,
      isWritable: true,
    },
    airdropMaster: { value: input.airdropMaster ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    masterCreator: { value: input.masterCreator ?? null, isWritable: false },
    airdrop: { value: input.airdrop ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.airdropConfig),
      getAccountMeta(accounts.protocolTreasury),
      getAccountMeta(accounts.airdropMaster),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.masterCreator),
      getAccountMeta(accounts.airdrop),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateAirdropInstructionDataEncoder().encode(
      args as CreateAirdropInstructionDataArgs,
    ),
    programAddress,
  } as CreateAirdropInstruction<
    TProgramAddress,
    TAccountAirdropConfig,
    TAccountProtocolTreasury,
    TAccountAirdropMaster,
    TAccountTreasury,
    TAccountMasterCreator,
    TAccountAirdrop,
    TAccountMint,
    TAccountAuthority,
    TAccountSystemProgram
  >);
}

export type ParsedCreateAirdropInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    airdropConfig: TAccountMetas[0];
    protocolTreasury: TAccountMetas[1];
    airdropMaster: TAccountMetas[2];
    treasury: TAccountMetas[3];
    masterCreator: TAccountMetas[4];
    airdrop: TAccountMetas[5];
    mint: TAccountMetas[6];
    authority: TAccountMetas[7];
    systemProgram: TAccountMetas[8];
  };
  data: CreateAirdropInstructionData;
};

export function parseCreateAirdropInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateAirdropInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      airdropConfig: getNextAccount(),
      protocolTreasury: getNextAccount(),
      airdropMaster: getNextAccount(),
      treasury: getNextAccount(),
      masterCreator: getNextAccount(),
      airdrop: getNextAccount(),
      mint: getNextAccount(),
      authority: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateAirdropInstructionDataDecoder().decode(instruction.data),
  };
}
