/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { DROPSY_AIRDROP_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getAirdropConfigInitArgsDecoder,
  getAirdropConfigInitArgsEncoder,
  type AirdropConfigInitArgs,
  type AirdropConfigInitArgsArgs,
} from "../types";

export const INITIALIZE_AIRDROP_CONFIG_DISCRIMINATOR = new Uint8Array([
  160, 68, 127, 205, 130, 205, 156, 94,
]);

export function getInitializeAirdropConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_AIRDROP_CONFIG_DISCRIMINATOR,
  );
}

export type InitializeAirdropConfigInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountProtocolTreasury extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> =
    "6TMmpVof9fGXak2VUgP4X9sXNfPHA7XWyi9ZMUCrHP6A",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountProtocolTreasury extends string
        ? ReadonlyAccount<TAccountProtocolTreasury>
        : TAccountProtocolTreasury,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeAirdropConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  args: AirdropConfigInitArgs;
};

export type InitializeAirdropConfigInstructionDataArgs = {
  args: AirdropConfigInitArgsArgs;
};

export function getInitializeAirdropConfigInstructionDataEncoder(): Encoder<InitializeAirdropConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["args", getAirdropConfigInitArgsEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_AIRDROP_CONFIG_DISCRIMINATOR,
    }),
  );
}

export function getInitializeAirdropConfigInstructionDataDecoder(): Decoder<InitializeAirdropConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["args", getAirdropConfigInitArgsDecoder()],
  ]);
}

export function getInitializeAirdropConfigInstructionDataCodec(): Codec<
  InitializeAirdropConfigInstructionDataArgs,
  InitializeAirdropConfigInstructionData
> {
  return combineCodec(
    getInitializeAirdropConfigInstructionDataEncoder(),
    getInitializeAirdropConfigInstructionDataDecoder(),
  );
}

export type InitializeAirdropConfigAsyncInput<
  TAccountConfig extends string = string,
  TAccountProtocolTreasury extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  config?: Address<TAccountConfig>;
  protocolTreasury: Address<TAccountProtocolTreasury>;
  authority?: TransactionSigner<TAccountAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  args: InitializeAirdropConfigInstructionDataArgs["args"];
};

export async function getInitializeAirdropConfigInstructionAsync<
  TAccountConfig extends string,
  TAccountProtocolTreasury extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: InitializeAirdropConfigAsyncInput<
    TAccountConfig,
    TAccountProtocolTreasury,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeAirdropConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountProtocolTreasury,
    TAccountAuthority,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    protocolTreasury: {
      value: input.protocolTreasury ?? null,
      isWritable: false,
    },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 105, 114, 100, 114, 111, 112, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.authority.value) {
    accounts.authority.value =
      "6TMmpVof9fGXak2VUgP4X9sXNfPHA7XWyi9ZMUCrHP6A" as Address<"6TMmpVof9fGXak2VUgP4X9sXNfPHA7XWyi9ZMUCrHP6A">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.protocolTreasury),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeAirdropConfigInstructionDataEncoder().encode(
      args as InitializeAirdropConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitializeAirdropConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountProtocolTreasury,
    TAccountAuthority,
    TAccountSystemProgram
  >);
}

export type InitializeAirdropConfigInput<
  TAccountConfig extends string = string,
  TAccountProtocolTreasury extends string = string,
  TAccountAuthority extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  config: Address<TAccountConfig>;
  protocolTreasury: Address<TAccountProtocolTreasury>;
  authority?: TransactionSigner<TAccountAuthority>;
  systemProgram?: Address<TAccountSystemProgram>;
  args: InitializeAirdropConfigInstructionDataArgs["args"];
};

export function getInitializeAirdropConfigInstruction<
  TAccountConfig extends string,
  TAccountProtocolTreasury extends string,
  TAccountAuthority extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: InitializeAirdropConfigInput<
    TAccountConfig,
    TAccountProtocolTreasury,
    TAccountAuthority,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeAirdropConfigInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountProtocolTreasury,
  TAccountAuthority,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    protocolTreasury: {
      value: input.protocolTreasury ?? null,
      isWritable: false,
    },
    authority: { value: input.authority ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.authority.value) {
    accounts.authority.value =
      "6TMmpVof9fGXak2VUgP4X9sXNfPHA7XWyi9ZMUCrHP6A" as Address<"6TMmpVof9fGXak2VUgP4X9sXNfPHA7XWyi9ZMUCrHP6A">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.protocolTreasury),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeAirdropConfigInstructionDataEncoder().encode(
      args as InitializeAirdropConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitializeAirdropConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountProtocolTreasury,
    TAccountAuthority,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeAirdropConfigInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    protocolTreasury: TAccountMetas[1];
    authority: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: InitializeAirdropConfigInstructionData;
};

export function parseInitializeAirdropConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeAirdropConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      protocolTreasury: getNextAccount(),
      authority: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeAirdropConfigInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
