/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { DROPSY_AIRDROP_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const INITIALIZE_AIRDROP_MASTER_DISCRIMINATOR = new Uint8Array([
  163, 197, 170, 44, 57, 57, 90, 65,
]);

export function getInitializeAirdropMasterDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_AIRDROP_MASTER_DISCRIMINATOR,
  );
}

export type InitializeAirdropMasterInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountAirdropMaster extends string | AccountMeta<string> = string,
  TAccountProtocolTreasury extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountAffiliate extends string | AccountMeta<string> = string,
  TAccountMasterCreator extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountAirdropMaster extends string
        ? WritableAccount<TAccountAirdropMaster>
        : TAccountAirdropMaster,
      TAccountProtocolTreasury extends string
        ? WritableAccount<TAccountProtocolTreasury>
        : TAccountProtocolTreasury,
      TAccountTreasury extends string
        ? ReadonlyAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountAffiliate extends string
        ? WritableAccount<TAccountAffiliate>
        : TAccountAffiliate,
      TAccountMasterCreator extends string
        ? WritableSignerAccount<TAccountMasterCreator> &
            AccountSignerMeta<TAccountMasterCreator>
        : TAccountMasterCreator,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeAirdropMasterInstructionData = {
  discriminator: ReadonlyUint8Array;
  airdropUpdateFee: Option<bigint>;
  airdropCreationFee: Option<bigint>;
  airdropClaimFee: Option<bigint>;
  airdropDelegateFee: Option<bigint>;
  bitmapCreationFee: Option<bigint>;
  discountProof: Option<Array<ReadonlyUint8Array>>;
};

export type InitializeAirdropMasterInstructionDataArgs = {
  airdropUpdateFee: OptionOrNullable<number | bigint>;
  airdropCreationFee: OptionOrNullable<number | bigint>;
  airdropClaimFee: OptionOrNullable<number | bigint>;
  airdropDelegateFee: OptionOrNullable<number | bigint>;
  bitmapCreationFee: OptionOrNullable<number | bigint>;
  discountProof: OptionOrNullable<Array<ReadonlyUint8Array>>;
};

export function getInitializeAirdropMasterInstructionDataEncoder(): Encoder<InitializeAirdropMasterInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["airdropUpdateFee", getOptionEncoder(getU64Encoder())],
      ["airdropCreationFee", getOptionEncoder(getU64Encoder())],
      ["airdropClaimFee", getOptionEncoder(getU64Encoder())],
      ["airdropDelegateFee", getOptionEncoder(getU64Encoder())],
      ["bitmapCreationFee", getOptionEncoder(getU64Encoder())],
      [
        "discountProof",
        getOptionEncoder(
          getArrayEncoder(fixEncoderSize(getBytesEncoder(), 32)),
        ),
      ],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_AIRDROP_MASTER_DISCRIMINATOR,
    }),
  );
}

export function getInitializeAirdropMasterInstructionDataDecoder(): Decoder<InitializeAirdropMasterInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["airdropUpdateFee", getOptionDecoder(getU64Decoder())],
    ["airdropCreationFee", getOptionDecoder(getU64Decoder())],
    ["airdropClaimFee", getOptionDecoder(getU64Decoder())],
    ["airdropDelegateFee", getOptionDecoder(getU64Decoder())],
    ["bitmapCreationFee", getOptionDecoder(getU64Decoder())],
    [
      "discountProof",
      getOptionDecoder(getArrayDecoder(fixDecoderSize(getBytesDecoder(), 32))),
    ],
  ]);
}

export function getInitializeAirdropMasterInstructionDataCodec(): Codec<
  InitializeAirdropMasterInstructionDataArgs,
  InitializeAirdropMasterInstructionData
> {
  return combineCodec(
    getInitializeAirdropMasterInstructionDataEncoder(),
    getInitializeAirdropMasterInstructionDataDecoder(),
  );
}

export type InitializeAirdropMasterAsyncInput<
  TAccountConfig extends string = string,
  TAccountAirdropMaster extends string = string,
  TAccountProtocolTreasury extends string = string,
  TAccountTreasury extends string = string,
  TAccountAffiliate extends string = string,
  TAccountMasterCreator extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  config?: Address<TAccountConfig>;
  airdropMaster?: Address<TAccountAirdropMaster>;
  protocolTreasury: Address<TAccountProtocolTreasury>;
  treasury: Address<TAccountTreasury>;
  affiliate?: Address<TAccountAffiliate>;
  masterCreator: TransactionSigner<TAccountMasterCreator>;
  systemProgram?: Address<TAccountSystemProgram>;
  airdropUpdateFee: InitializeAirdropMasterInstructionDataArgs["airdropUpdateFee"];
  airdropCreationFee: InitializeAirdropMasterInstructionDataArgs["airdropCreationFee"];
  airdropClaimFee: InitializeAirdropMasterInstructionDataArgs["airdropClaimFee"];
  airdropDelegateFee: InitializeAirdropMasterInstructionDataArgs["airdropDelegateFee"];
  bitmapCreationFee: InitializeAirdropMasterInstructionDataArgs["bitmapCreationFee"];
  discountProof: InitializeAirdropMasterInstructionDataArgs["discountProof"];
};

export async function getInitializeAirdropMasterInstructionAsync<
  TAccountConfig extends string,
  TAccountAirdropMaster extends string,
  TAccountProtocolTreasury extends string,
  TAccountTreasury extends string,
  TAccountAffiliate extends string,
  TAccountMasterCreator extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: InitializeAirdropMasterAsyncInput<
    TAccountConfig,
    TAccountAirdropMaster,
    TAccountProtocolTreasury,
    TAccountTreasury,
    TAccountAffiliate,
    TAccountMasterCreator,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeAirdropMasterInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAirdropMaster,
    TAccountProtocolTreasury,
    TAccountTreasury,
    TAccountAffiliate,
    TAccountMasterCreator,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    airdropMaster: { value: input.airdropMaster ?? null, isWritable: true },
    protocolTreasury: {
      value: input.protocolTreasury ?? null,
      isWritable: true,
    },
    treasury: { value: input.treasury ?? null, isWritable: false },
    affiliate: { value: input.affiliate ?? null, isWritable: true },
    masterCreator: { value: input.masterCreator ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 105, 114, 100, 114, 111, 112, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.airdropMaster.value) {
    accounts.airdropMaster.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 105, 114, 100, 114, 111, 112, 95, 109, 97, 115, 116, 101, 114,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.masterCreator.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.airdropMaster),
      getAccountMeta(accounts.protocolTreasury),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.affiliate),
      getAccountMeta(accounts.masterCreator),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeAirdropMasterInstructionDataEncoder().encode(
      args as InitializeAirdropMasterInstructionDataArgs,
    ),
    programAddress,
  } as InitializeAirdropMasterInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAirdropMaster,
    TAccountProtocolTreasury,
    TAccountTreasury,
    TAccountAffiliate,
    TAccountMasterCreator,
    TAccountSystemProgram
  >);
}

export type InitializeAirdropMasterInput<
  TAccountConfig extends string = string,
  TAccountAirdropMaster extends string = string,
  TAccountProtocolTreasury extends string = string,
  TAccountTreasury extends string = string,
  TAccountAffiliate extends string = string,
  TAccountMasterCreator extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  config: Address<TAccountConfig>;
  airdropMaster: Address<TAccountAirdropMaster>;
  protocolTreasury: Address<TAccountProtocolTreasury>;
  treasury: Address<TAccountTreasury>;
  affiliate?: Address<TAccountAffiliate>;
  masterCreator: TransactionSigner<TAccountMasterCreator>;
  systemProgram?: Address<TAccountSystemProgram>;
  airdropUpdateFee: InitializeAirdropMasterInstructionDataArgs["airdropUpdateFee"];
  airdropCreationFee: InitializeAirdropMasterInstructionDataArgs["airdropCreationFee"];
  airdropClaimFee: InitializeAirdropMasterInstructionDataArgs["airdropClaimFee"];
  airdropDelegateFee: InitializeAirdropMasterInstructionDataArgs["airdropDelegateFee"];
  bitmapCreationFee: InitializeAirdropMasterInstructionDataArgs["bitmapCreationFee"];
  discountProof: InitializeAirdropMasterInstructionDataArgs["discountProof"];
};

export function getInitializeAirdropMasterInstruction<
  TAccountConfig extends string,
  TAccountAirdropMaster extends string,
  TAccountProtocolTreasury extends string,
  TAccountTreasury extends string,
  TAccountAffiliate extends string,
  TAccountMasterCreator extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: InitializeAirdropMasterInput<
    TAccountConfig,
    TAccountAirdropMaster,
    TAccountProtocolTreasury,
    TAccountTreasury,
    TAccountAffiliate,
    TAccountMasterCreator,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeAirdropMasterInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountAirdropMaster,
  TAccountProtocolTreasury,
  TAccountTreasury,
  TAccountAffiliate,
  TAccountMasterCreator,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    airdropMaster: { value: input.airdropMaster ?? null, isWritable: true },
    protocolTreasury: {
      value: input.protocolTreasury ?? null,
      isWritable: true,
    },
    treasury: { value: input.treasury ?? null, isWritable: false },
    affiliate: { value: input.affiliate ?? null, isWritable: true },
    masterCreator: { value: input.masterCreator ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.airdropMaster),
      getAccountMeta(accounts.protocolTreasury),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.affiliate),
      getAccountMeta(accounts.masterCreator),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeAirdropMasterInstructionDataEncoder().encode(
      args as InitializeAirdropMasterInstructionDataArgs,
    ),
    programAddress,
  } as InitializeAirdropMasterInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAirdropMaster,
    TAccountProtocolTreasury,
    TAccountTreasury,
    TAccountAffiliate,
    TAccountMasterCreator,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeAirdropMasterInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    airdropMaster: TAccountMetas[1];
    protocolTreasury: TAccountMetas[2];
    treasury: TAccountMetas[3];
    affiliate?: TAccountMetas[4] | undefined;
    masterCreator: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: InitializeAirdropMasterInstructionData;
};

export function parseInitializeAirdropMasterInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeAirdropMasterInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === DROPSY_AIRDROP_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      airdropMaster: getNextAccount(),
      protocolTreasury: getNextAccount(),
      treasury: getNextAccount(),
      affiliate: getNextOptionalAccount(),
      masterCreator: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeAirdropMasterInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
