/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { DROPSY_AIRDROP_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getAirdropConfigInitArgsDecoder,
  getAirdropConfigInitArgsEncoder,
  type AirdropConfigInitArgs,
  type AirdropConfigInitArgsArgs,
} from "../types";

export const UPDATE_AIRDROP_CONFIG_DISCRIMINATOR = new Uint8Array([
  115, 114, 134, 61, 40, 17, 128, 142,
]);

export function getUpdateAirdropConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_AIRDROP_CONFIG_DISCRIMINATOR,
  );
}

export type UpdateAirdropConfigInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> =
    "6TMmpVof9fGXak2VUgP4X9sXNfPHA7XWyi9ZMUCrHP6A",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateAirdropConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  args: AirdropConfigInitArgs;
};

export type UpdateAirdropConfigInstructionDataArgs = {
  args: AirdropConfigInitArgsArgs;
};

export function getUpdateAirdropConfigInstructionDataEncoder(): Encoder<UpdateAirdropConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["args", getAirdropConfigInitArgsEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_AIRDROP_CONFIG_DISCRIMINATOR,
    }),
  );
}

export function getUpdateAirdropConfigInstructionDataDecoder(): Decoder<UpdateAirdropConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["args", getAirdropConfigInitArgsDecoder()],
  ]);
}

export function getUpdateAirdropConfigInstructionDataCodec(): Codec<
  UpdateAirdropConfigInstructionDataArgs,
  UpdateAirdropConfigInstructionData
> {
  return combineCodec(
    getUpdateAirdropConfigInstructionDataEncoder(),
    getUpdateAirdropConfigInstructionDataDecoder(),
  );
}

export type UpdateAirdropConfigAsyncInput<
  TAccountConfig extends string = string,
  TAccountAuthority extends string = string,
> = {
  config?: Address<TAccountConfig>;
  authority?: TransactionSigner<TAccountAuthority>;
  args: UpdateAirdropConfigInstructionDataArgs["args"];
};

export async function getUpdateAirdropConfigInstructionAsync<
  TAccountConfig extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: UpdateAirdropConfigAsyncInput<TAccountConfig, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  UpdateAirdropConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAuthority
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            97, 105, 114, 100, 114, 111, 112, 95, 99, 111, 110, 102, 105, 103,
          ]),
        ),
      ],
    });
  }
  if (!accounts.authority.value) {
    accounts.authority.value =
      "6TMmpVof9fGXak2VUgP4X9sXNfPHA7XWyi9ZMUCrHP6A" as Address<"6TMmpVof9fGXak2VUgP4X9sXNfPHA7XWyi9ZMUCrHP6A">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.authority),
    ],
    data: getUpdateAirdropConfigInstructionDataEncoder().encode(
      args as UpdateAirdropConfigInstructionDataArgs,
    ),
    programAddress,
  } as UpdateAirdropConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAuthority
  >);
}

export type UpdateAirdropConfigInput<
  TAccountConfig extends string = string,
  TAccountAuthority extends string = string,
> = {
  config: Address<TAccountConfig>;
  authority?: TransactionSigner<TAccountAuthority>;
  args: UpdateAirdropConfigInstructionDataArgs["args"];
};

export function getUpdateAirdropConfigInstruction<
  TAccountConfig extends string,
  TAccountAuthority extends string,
  TProgramAddress extends Address = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
>(
  input: UpdateAirdropConfigInput<TAccountConfig, TAccountAuthority>,
  config?: { programAddress?: TProgramAddress },
): UpdateAirdropConfigInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountAuthority
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? DROPSY_AIRDROP_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.authority.value) {
    accounts.authority.value =
      "6TMmpVof9fGXak2VUgP4X9sXNfPHA7XWyi9ZMUCrHP6A" as Address<"6TMmpVof9fGXak2VUgP4X9sXNfPHA7XWyi9ZMUCrHP6A">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.authority),
    ],
    data: getUpdateAirdropConfigInstructionDataEncoder().encode(
      args as UpdateAirdropConfigInstructionDataArgs,
    ),
    programAddress,
  } as UpdateAirdropConfigInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountAuthority
  >);
}

export type ParsedUpdateAirdropConfigInstruction<
  TProgram extends string = typeof DROPSY_AIRDROP_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    authority: TAccountMetas[1];
  };
  data: UpdateAirdropConfigInstructionData;
};

export function parseUpdateAirdropConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateAirdropConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { config: getNextAccount(), authority: getNextAccount() },
    data: getUpdateAirdropConfigInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
