/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseClaimAirdropInstruction,
  parseCreateAirdropInstruction,
  parseCreateBitmapInstruction,
  parseDepositTokensInstruction,
  parseInitializeAirdropConfigInstruction,
  parseInitializeAirdropMasterInstruction,
  parseUpdateAirdropConfigInstruction,
  type ParsedClaimAirdropInstruction,
  type ParsedCreateAirdropInstruction,
  type ParsedCreateBitmapInstruction,
  type ParsedDepositTokensInstruction,
  type ParsedInitializeAirdropConfigInstruction,
  type ParsedInitializeAirdropMasterInstruction,
  type ParsedUpdateAirdropConfigInstruction,
} from "../instructions";

export const DROPSY_AIRDROP_PROGRAM_ADDRESS =
  "drophxkcW5TRfbMQgo45Yti3q8jVxuxvuNufMnu8WiE" as Address<"drophxkcW5TRfbMQgo45Yti3q8jVxuxvuNufMnu8WiE">;

export enum DropsyAirdropAccount {
  Airdrop,
  AirdropConfig,
  AirdropMaster,
  BitmapAccount,
}

export function identifyDropsyAirdropAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): DropsyAirdropAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([31, 112, 159, 158, 124, 237, 9, 241]),
      ),
      0,
    )
  ) {
    return DropsyAirdropAccount.Airdrop;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([194, 149, 223, 142, 42, 98, 128, 16]),
      ),
      0,
    )
  ) {
    return DropsyAirdropAccount.AirdropConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([31, 109, 100, 62, 106, 173, 5, 4]),
      ),
      0,
    )
  ) {
    return DropsyAirdropAccount.AirdropMaster;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([152, 161, 147, 85, 213, 38, 59, 48]),
      ),
      0,
    )
  ) {
    return DropsyAirdropAccount.BitmapAccount;
  }
  throw new Error(
    "The provided account could not be identified as a dropsyAirdrop account.",
  );
}

export enum DropsyAirdropInstruction {
  ClaimAirdrop,
  CreateAirdrop,
  CreateBitmap,
  DepositTokens,
  InitializeAirdropConfig,
  InitializeAirdropMaster,
  UpdateAirdropConfig,
}

export function identifyDropsyAirdropInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): DropsyAirdropInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([137, 50, 122, 111, 89, 254, 8, 20]),
      ),
      0,
    )
  ) {
    return DropsyAirdropInstruction.ClaimAirdrop;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([227, 135, 208, 66, 137, 177, 80, 94]),
      ),
      0,
    )
  ) {
    return DropsyAirdropInstruction.CreateAirdrop;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([69, 92, 61, 190, 154, 237, 116, 247]),
      ),
      0,
    )
  ) {
    return DropsyAirdropInstruction.CreateBitmap;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([176, 83, 229, 18, 191, 143, 176, 150]),
      ),
      0,
    )
  ) {
    return DropsyAirdropInstruction.DepositTokens;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([160, 68, 127, 205, 130, 205, 156, 94]),
      ),
      0,
    )
  ) {
    return DropsyAirdropInstruction.InitializeAirdropConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([163, 197, 170, 44, 57, 57, 90, 65]),
      ),
      0,
    )
  ) {
    return DropsyAirdropInstruction.InitializeAirdropMaster;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([115, 114, 134, 61, 40, 17, 128, 142]),
      ),
      0,
    )
  ) {
    return DropsyAirdropInstruction.UpdateAirdropConfig;
  }
  throw new Error(
    "The provided instruction could not be identified as a dropsyAirdrop instruction.",
  );
}

export type ParsedDropsyAirdropInstruction<
  TProgram extends string = "3b97gLF94DDpa7sJQ8orbE3Ab6JQWBsDQTdQ5azoZqcz",
> =
  | ({
      instructionType: DropsyAirdropInstruction.ClaimAirdrop;
    } & ParsedClaimAirdropInstruction<TProgram>)
  | ({
      instructionType: DropsyAirdropInstruction.CreateAirdrop;
    } & ParsedCreateAirdropInstruction<TProgram>)
  | ({
      instructionType: DropsyAirdropInstruction.CreateBitmap;
    } & ParsedCreateBitmapInstruction<TProgram>)
  | ({
      instructionType: DropsyAirdropInstruction.DepositTokens;
    } & ParsedDepositTokensInstruction<TProgram>)
  | ({
      instructionType: DropsyAirdropInstruction.InitializeAirdropConfig;
    } & ParsedInitializeAirdropConfigInstruction<TProgram>)
  | ({
      instructionType: DropsyAirdropInstruction.InitializeAirdropMaster;
    } & ParsedInitializeAirdropMasterInstruction<TProgram>)
  | ({
      instructionType: DropsyAirdropInstruction.UpdateAirdropConfig;
    } & ParsedUpdateAirdropConfigInstruction<TProgram>);

export function parseDropsyAirdropInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedDropsyAirdropInstruction<TProgram> {
  const instructionType = identifyDropsyAirdropInstruction(instruction);
  switch (instructionType) {
    case DropsyAirdropInstruction.ClaimAirdrop: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: DropsyAirdropInstruction.ClaimAirdrop,
        ...parseClaimAirdropInstruction(instruction),
      };
    }
    case DropsyAirdropInstruction.CreateAirdrop: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: DropsyAirdropInstruction.CreateAirdrop,
        ...parseCreateAirdropInstruction(instruction),
      };
    }
    case DropsyAirdropInstruction.CreateBitmap: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: DropsyAirdropInstruction.CreateBitmap,
        ...parseCreateBitmapInstruction(instruction),
      };
    }
    case DropsyAirdropInstruction.DepositTokens: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: DropsyAirdropInstruction.DepositTokens,
        ...parseDepositTokensInstruction(instruction),
      };
    }
    case DropsyAirdropInstruction.InitializeAirdropConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: DropsyAirdropInstruction.InitializeAirdropConfig,
        ...parseInitializeAirdropConfigInstruction(instruction),
      };
    }
    case DropsyAirdropInstruction.InitializeAirdropMaster: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: DropsyAirdropInstruction.InitializeAirdropMaster,
        ...parseInitializeAirdropMasterInstruction(instruction),
      };
    }
    case DropsyAirdropInstruction.UpdateAirdropConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: DropsyAirdropInstruction.UpdateAirdropConfig,
        ...parseUpdateAirdropConfigInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
