/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const AIRDROP_MASTER_DISCRIMINATOR = new Uint8Array([
  31, 109, 100, 62, 106, 173, 5, 4,
]);

export function getAirdropMasterDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    AIRDROP_MASTER_DISCRIMINATOR,
  );
}

export type AirdropMaster = {
  discriminator: ReadonlyUint8Array;
  creator: Address;
  authority: Address;
  treasury: Address;
  createdAirdrops: bigint;
  points: bigint;
  totalClaimCount: bigint;
  airdropUpdateFee: bigint;
  airdropCreationFee: bigint;
  airdropClaimFee: bigint;
  bitmapCreationFee: bigint;
  bump: number;
  padding: ReadonlyUint8Array;
  reserved: ReadonlyUint8Array;
};

export type AirdropMasterArgs = {
  creator: Address;
  authority: Address;
  treasury: Address;
  createdAirdrops: number | bigint;
  points: number | bigint;
  totalClaimCount: number | bigint;
  airdropUpdateFee: number | bigint;
  airdropCreationFee: number | bigint;
  airdropClaimFee: number | bigint;
  bitmapCreationFee: number | bigint;
  bump: number;
  padding: ReadonlyUint8Array;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link AirdropMasterArgs} account data. */
export function getAirdropMasterEncoder(): FixedSizeEncoder<AirdropMasterArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["creator", getAddressEncoder()],
      ["authority", getAddressEncoder()],
      ["treasury", getAddressEncoder()],
      ["createdAirdrops", getU64Encoder()],
      ["points", getU64Encoder()],
      ["totalClaimCount", getU64Encoder()],
      ["airdropUpdateFee", getU64Encoder()],
      ["airdropCreationFee", getU64Encoder()],
      ["airdropClaimFee", getU64Encoder()],
      ["bitmapCreationFee", getU64Encoder()],
      ["bump", getU8Encoder()],
      ["padding", fixEncoderSize(getBytesEncoder(), 7)],
      ["reserved", fixEncoderSize(getBytesEncoder(), 128)],
    ]),
    (value) => ({ ...value, discriminator: AIRDROP_MASTER_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link AirdropMaster} account data. */
export function getAirdropMasterDecoder(): FixedSizeDecoder<AirdropMaster> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["creator", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["treasury", getAddressDecoder()],
    ["createdAirdrops", getU64Decoder()],
    ["points", getU64Decoder()],
    ["totalClaimCount", getU64Decoder()],
    ["airdropUpdateFee", getU64Decoder()],
    ["airdropCreationFee", getU64Decoder()],
    ["airdropClaimFee", getU64Decoder()],
    ["bitmapCreationFee", getU64Decoder()],
    ["bump", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 7)],
    ["reserved", fixDecoderSize(getBytesDecoder(), 128)],
  ]);
}

/** Gets the codec for {@link AirdropMaster} account data. */
export function getAirdropMasterCodec(): FixedSizeCodec<
  AirdropMasterArgs,
  AirdropMaster
> {
  return combineCodec(getAirdropMasterEncoder(), getAirdropMasterDecoder());
}

export function decodeAirdropMaster<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<AirdropMaster, TAddress>;
export function decodeAirdropMaster<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<AirdropMaster, TAddress>;
export function decodeAirdropMaster<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<AirdropMaster, TAddress> | MaybeAccount<AirdropMaster, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getAirdropMasterDecoder(),
  );
}

export async function fetchAirdropMaster<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<AirdropMaster, TAddress>> {
  const maybeAccount = await fetchMaybeAirdropMaster(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeAirdropMaster<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<AirdropMaster, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeAirdropMaster(maybeAccount);
}

export async function fetchAllAirdropMaster(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<AirdropMaster>[]> {
  const maybeAccounts = await fetchAllMaybeAirdropMaster(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeAirdropMaster(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<AirdropMaster>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeAirdropMaster(maybeAccount));
}

export function getAirdropMasterSize(): number {
  return 296;
}
