/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const AIRDROP_CONFIG_DISCRIMINATOR = new Uint8Array([
  194, 149, 223, 142, 42, 98, 128, 16,
]);

export function getAirdropConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    AIRDROP_CONFIG_DISCRIMINATOR,
  );
}

export type AirdropConfig = {
  discriminator: ReadonlyUint8Array;
  authority: Address;
  protocolTreasury: Address;
  wlRoot: ReadonlyUint8Array;
  protocolFee: bigint;
  airdropMasterCreateFee: bigint;
  maxClaimFee: bigint;
  maxActionFee: bigint;
  minAirdropDuration: bigint;
  defaultAirdropDuration: bigint;
  maxAirdropDuration: bigint;
  updateGracePeriod: bigint;
  masterFeeBps: number;
  version: number;
  bump: number;
  padding: ReadonlyUint8Array;
  reserved: ReadonlyUint8Array;
};

export type AirdropConfigArgs = {
  authority: Address;
  protocolTreasury: Address;
  wlRoot: ReadonlyUint8Array;
  protocolFee: number | bigint;
  airdropMasterCreateFee: number | bigint;
  maxClaimFee: number | bigint;
  maxActionFee: number | bigint;
  minAirdropDuration: number | bigint;
  defaultAirdropDuration: number | bigint;
  maxAirdropDuration: number | bigint;
  updateGracePeriod: number | bigint;
  masterFeeBps: number;
  version: number;
  bump: number;
  padding: ReadonlyUint8Array;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link AirdropConfigArgs} account data. */
export function getAirdropConfigEncoder(): FixedSizeEncoder<AirdropConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["authority", getAddressEncoder()],
      ["protocolTreasury", getAddressEncoder()],
      ["wlRoot", fixEncoderSize(getBytesEncoder(), 32)],
      ["protocolFee", getU64Encoder()],
      ["airdropMasterCreateFee", getU64Encoder()],
      ["maxClaimFee", getU64Encoder()],
      ["maxActionFee", getU64Encoder()],
      ["minAirdropDuration", getI64Encoder()],
      ["defaultAirdropDuration", getI64Encoder()],
      ["maxAirdropDuration", getI64Encoder()],
      ["updateGracePeriod", getI64Encoder()],
      ["masterFeeBps", getU16Encoder()],
      ["version", getU8Encoder()],
      ["bump", getU8Encoder()],
      ["padding", fixEncoderSize(getBytesEncoder(), 4)],
      ["reserved", fixEncoderSize(getBytesEncoder(), 256)],
    ]),
    (value) => ({ ...value, discriminator: AIRDROP_CONFIG_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link AirdropConfig} account data. */
export function getAirdropConfigDecoder(): FixedSizeDecoder<AirdropConfig> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["authority", getAddressDecoder()],
    ["protocolTreasury", getAddressDecoder()],
    ["wlRoot", fixDecoderSize(getBytesDecoder(), 32)],
    ["protocolFee", getU64Decoder()],
    ["airdropMasterCreateFee", getU64Decoder()],
    ["maxClaimFee", getU64Decoder()],
    ["maxActionFee", getU64Decoder()],
    ["minAirdropDuration", getI64Decoder()],
    ["defaultAirdropDuration", getI64Decoder()],
    ["maxAirdropDuration", getI64Decoder()],
    ["updateGracePeriod", getI64Decoder()],
    ["masterFeeBps", getU16Decoder()],
    ["version", getU8Decoder()],
    ["bump", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 4)],
    ["reserved", fixDecoderSize(getBytesDecoder(), 256)],
  ]);
}

/** Gets the codec for {@link AirdropConfig} account data. */
export function getAirdropConfigCodec(): FixedSizeCodec<
  AirdropConfigArgs,
  AirdropConfig
> {
  return combineCodec(getAirdropConfigEncoder(), getAirdropConfigDecoder());
}

export function decodeAirdropConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<AirdropConfig, TAddress>;
export function decodeAirdropConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<AirdropConfig, TAddress>;
export function decodeAirdropConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<AirdropConfig, TAddress> | MaybeAccount<AirdropConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getAirdropConfigDecoder(),
  );
}

export async function fetchAirdropConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<AirdropConfig, TAddress>> {
  const maybeAccount = await fetchMaybeAirdropConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeAirdropConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<AirdropConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeAirdropConfig(maybeAccount);
}

export async function fetchAllAirdropConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<AirdropConfig>[]> {
  const maybeAccounts = await fetchAllMaybeAirdropConfig(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeAirdropConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<AirdropConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeAirdropConfig(maybeAccount));
}

export function getAirdropConfigSize(): number {
  return 432;
}
