/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const AIRDROP_DISCRIMINATOR = new Uint8Array([
  31, 112, 159, 158, 124, 237, 9, 241,
]);

export function getAirdropDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(AIRDROP_DISCRIMINATOR);
}

export type Airdrop = {
  discriminator: ReadonlyUint8Array;
  master: Address;
  authority: Address;
  mint: Address;
  delegateAuthority: Address;
  merkleRoot: ReadonlyUint8Array;
  id: bigint;
  supply: bigint;
  boost: bigint;
  startsAt: bigint;
  endsAt: bigint;
  bitmapCount: number;
  state: number;
  version: number;
  delegatePermissions: number;
  bump: number;
  padding: ReadonlyUint8Array;
};

export type AirdropArgs = {
  master: Address;
  authority: Address;
  mint: Address;
  delegateAuthority: Address;
  merkleRoot: ReadonlyUint8Array;
  id: number | bigint;
  supply: number | bigint;
  boost: number | bigint;
  startsAt: number | bigint;
  endsAt: number | bigint;
  bitmapCount: number;
  state: number;
  version: number;
  delegatePermissions: number;
  bump: number;
  padding: ReadonlyUint8Array;
};

/** Gets the encoder for {@link AirdropArgs} account data. */
export function getAirdropEncoder(): FixedSizeEncoder<AirdropArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["master", getAddressEncoder()],
      ["authority", getAddressEncoder()],
      ["mint", getAddressEncoder()],
      ["delegateAuthority", getAddressEncoder()],
      ["merkleRoot", fixEncoderSize(getBytesEncoder(), 32)],
      ["id", getU64Encoder()],
      ["supply", getU64Encoder()],
      ["boost", getU64Encoder()],
      ["startsAt", getI64Encoder()],
      ["endsAt", getI64Encoder()],
      ["bitmapCount", getU16Encoder()],
      ["state", getU8Encoder()],
      ["version", getU8Encoder()],
      ["delegatePermissions", getU8Encoder()],
      ["bump", getU8Encoder()],
      ["padding", fixEncoderSize(getBytesEncoder(), 2)],
    ]),
    (value) => ({ ...value, discriminator: AIRDROP_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Airdrop} account data. */
export function getAirdropDecoder(): FixedSizeDecoder<Airdrop> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["master", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["delegateAuthority", getAddressDecoder()],
    ["merkleRoot", fixDecoderSize(getBytesDecoder(), 32)],
    ["id", getU64Decoder()],
    ["supply", getU64Decoder()],
    ["boost", getU64Decoder()],
    ["startsAt", getI64Decoder()],
    ["endsAt", getI64Decoder()],
    ["bitmapCount", getU16Decoder()],
    ["state", getU8Decoder()],
    ["version", getU8Decoder()],
    ["delegatePermissions", getU8Decoder()],
    ["bump", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 2)],
  ]);
}

/** Gets the codec for {@link Airdrop} account data. */
export function getAirdropCodec(): FixedSizeCodec<AirdropArgs, Airdrop> {
  return combineCodec(getAirdropEncoder(), getAirdropDecoder());
}

export function decodeAirdrop<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Airdrop, TAddress>;
export function decodeAirdrop<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Airdrop, TAddress>;
export function decodeAirdrop<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Airdrop, TAddress> | MaybeAccount<Airdrop, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getAirdropDecoder(),
  );
}

export async function fetchAirdrop<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Airdrop, TAddress>> {
  const maybeAccount = await fetchMaybeAirdrop(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeAirdrop<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Airdrop, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeAirdrop(maybeAccount);
}

export async function fetchAllAirdrop(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Airdrop>[]> {
  const maybeAccounts = await fetchAllMaybeAirdrop(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeAirdrop(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Airdrop>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeAirdrop(maybeAccount));
}

export function getAirdropSize(): number {
  return 216;
}
