/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const BITMAP_ACCOUNT_DISCRIMINATOR = new Uint8Array([
  152, 161, 147, 85, 213, 38, 59, 48,
]);

export function getBitmapAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    BITMAP_ACCOUNT_DISCRIMINATOR,
  );
}

export type BitmapAccount = {
  discriminator: ReadonlyUint8Array;
  authority: Address;
  airdrop: Address;
  total: number;
  claimedBitmap: ReadonlyUint8Array;
  id: number;
  version: number;
  bump: number;
};

export type BitmapAccountArgs = {
  authority: Address;
  airdrop: Address;
  total: number;
  claimedBitmap: ReadonlyUint8Array;
  id: number;
  version: number;
  bump: number;
};

/** Gets the encoder for {@link BitmapAccountArgs} account data. */
export function getBitmapAccountEncoder(): FixedSizeEncoder<BitmapAccountArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["authority", getAddressEncoder()],
      ["airdrop", getAddressEncoder()],
      ["total", getU32Encoder()],
      ["claimedBitmap", fixEncoderSize(getBytesEncoder(), 1000)],
      ["id", getU16Encoder()],
      ["version", getU8Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: BITMAP_ACCOUNT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link BitmapAccount} account data. */
export function getBitmapAccountDecoder(): FixedSizeDecoder<BitmapAccount> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["authority", getAddressDecoder()],
    ["airdrop", getAddressDecoder()],
    ["total", getU32Decoder()],
    ["claimedBitmap", fixDecoderSize(getBytesDecoder(), 1000)],
    ["id", getU16Decoder()],
    ["version", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link BitmapAccount} account data. */
export function getBitmapAccountCodec(): FixedSizeCodec<
  BitmapAccountArgs,
  BitmapAccount
> {
  return combineCodec(getBitmapAccountEncoder(), getBitmapAccountDecoder());
}

export function decodeBitmapAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<BitmapAccount, TAddress>;
export function decodeBitmapAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<BitmapAccount, TAddress>;
export function decodeBitmapAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<BitmapAccount, TAddress> | MaybeAccount<BitmapAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getBitmapAccountDecoder(),
  );
}

export async function fetchBitmapAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<BitmapAccount, TAddress>> {
  const maybeAccount = await fetchMaybeBitmapAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeBitmapAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<BitmapAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeBitmapAccount(maybeAccount);
}

export async function fetchAllBitmapAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<BitmapAccount>[]> {
  const maybeAccounts = await fetchAllMaybeBitmapAccount(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeBitmapAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<BitmapAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeBitmapAccount(maybeAccount));
}

export function getBitmapAccountSize(): number {
  return 1080;
}
