/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type AirdropInitialized = {
  airdrop: Address;
  mint: Address;
  authority: Address;
  master: Address;
  merkleRoot: ReadonlyUint8Array;
  startTime: bigint;
  endTime: bigint;
  timestamp: bigint;
};

export type AirdropInitializedArgs = {
  airdrop: Address;
  mint: Address;
  authority: Address;
  master: Address;
  merkleRoot: ReadonlyUint8Array;
  startTime: number | bigint;
  endTime: number | bigint;
  timestamp: number | bigint;
};

export function getAirdropInitializedEncoder(): FixedSizeEncoder<AirdropInitializedArgs> {
  return getStructEncoder([
    ["airdrop", getAddressEncoder()],
    ["mint", getAddressEncoder()],
    ["authority", getAddressEncoder()],
    ["master", getAddressEncoder()],
    ["merkleRoot", fixEncoderSize(getBytesEncoder(), 32)],
    ["startTime", getI64Encoder()],
    ["endTime", getI64Encoder()],
    ["timestamp", getI64Encoder()],
  ]);
}

export function getAirdropInitializedDecoder(): FixedSizeDecoder<AirdropInitialized> {
  return getStructDecoder([
    ["airdrop", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["master", getAddressDecoder()],
    ["merkleRoot", fixDecoderSize(getBytesDecoder(), 32)],
    ["startTime", getI64Decoder()],
    ["endTime", getI64Decoder()],
    ["timestamp", getI64Decoder()],
  ]);
}

export function getAirdropInitializedCodec(): FixedSizeCodec<
  AirdropInitializedArgs,
  AirdropInitialized
> {
  return combineCodec(
    getAirdropInitializedEncoder(),
    getAirdropInitializedDecoder(),
  );
}
