/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type AirdropConfigInitArgs = {
  wlRoot: Option<ReadonlyUint8Array>;
  airdropMasterCreateFee: Option<bigint>;
  maxClaimFee: Option<bigint>;
  maxActionFee: Option<bigint>;
  minAirdropDuration: Option<bigint>;
  defaultAirdropDuration: Option<bigint>;
  maxAirdropDuration: Option<bigint>;
  updateGracePeriod: Option<bigint>;
  protocolFee: Option<bigint>;
  masterFeeBps: Option<number>;
  protocolTreasury: Option<Address>;
};

export type AirdropConfigInitArgsArgs = {
  wlRoot: OptionOrNullable<ReadonlyUint8Array>;
  airdropMasterCreateFee: OptionOrNullable<number | bigint>;
  maxClaimFee: OptionOrNullable<number | bigint>;
  maxActionFee: OptionOrNullable<number | bigint>;
  minAirdropDuration: OptionOrNullable<number | bigint>;
  defaultAirdropDuration: OptionOrNullable<number | bigint>;
  maxAirdropDuration: OptionOrNullable<number | bigint>;
  updateGracePeriod: OptionOrNullable<number | bigint>;
  protocolFee: OptionOrNullable<number | bigint>;
  masterFeeBps: OptionOrNullable<number>;
  protocolTreasury: OptionOrNullable<Address>;
};

export function getAirdropConfigInitArgsEncoder(): Encoder<AirdropConfigInitArgsArgs> {
  return getStructEncoder([
    ["wlRoot", getOptionEncoder(fixEncoderSize(getBytesEncoder(), 32))],
    ["airdropMasterCreateFee", getOptionEncoder(getU64Encoder())],
    ["maxClaimFee", getOptionEncoder(getU64Encoder())],
    ["maxActionFee", getOptionEncoder(getU64Encoder())],
    ["minAirdropDuration", getOptionEncoder(getI64Encoder())],
    ["defaultAirdropDuration", getOptionEncoder(getI64Encoder())],
    ["maxAirdropDuration", getOptionEncoder(getI64Encoder())],
    ["updateGracePeriod", getOptionEncoder(getI64Encoder())],
    ["protocolFee", getOptionEncoder(getU64Encoder())],
    ["masterFeeBps", getOptionEncoder(getU16Encoder())],
    ["protocolTreasury", getOptionEncoder(getAddressEncoder())],
  ]);
}

export function getAirdropConfigInitArgsDecoder(): Decoder<AirdropConfigInitArgs> {
  return getStructDecoder([
    ["wlRoot", getOptionDecoder(fixDecoderSize(getBytesDecoder(), 32))],
    ["airdropMasterCreateFee", getOptionDecoder(getU64Decoder())],
    ["maxClaimFee", getOptionDecoder(getU64Decoder())],
    ["maxActionFee", getOptionDecoder(getU64Decoder())],
    ["minAirdropDuration", getOptionDecoder(getI64Decoder())],
    ["defaultAirdropDuration", getOptionDecoder(getI64Decoder())],
    ["maxAirdropDuration", getOptionDecoder(getI64Decoder())],
    ["updateGracePeriod", getOptionDecoder(getI64Decoder())],
    ["protocolFee", getOptionDecoder(getU64Decoder())],
    ["masterFeeBps", getOptionDecoder(getU16Decoder())],
    ["protocolTreasury", getOptionDecoder(getAddressDecoder())],
  ]);
}

export function getAirdropConfigInitArgsCodec(): Codec<
  AirdropConfigInitArgsArgs,
  AirdropConfigInitArgs
> {
  return combineCodec(
    getAirdropConfigInitArgsEncoder(),
    getAirdropConfigInitArgsDecoder(),
  );
}
