/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type BitmapClosed = {
  airdrop: Address;
  bitmap: Address;
  authority: Address;
};

export type BitmapClosedArgs = BitmapClosed;

export function getBitmapClosedEncoder(): FixedSizeEncoder<BitmapClosedArgs> {
  return getStructEncoder([
    ["airdrop", getAddressEncoder()],
    ["bitmap", getAddressEncoder()],
    ["authority", getAddressEncoder()],
  ]);
}

export function getBitmapClosedDecoder(): FixedSizeDecoder<BitmapClosed> {
  return getStructDecoder([
    ["airdrop", getAddressDecoder()],
    ["bitmap", getAddressDecoder()],
    ["authority", getAddressDecoder()],
  ]);
}

export function getBitmapClosedCodec(): FixedSizeCodec<
  BitmapClosedArgs,
  BitmapClosed
> {
  return combineCodec(getBitmapClosedEncoder(), getBitmapClosedDecoder());
}
