/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type BitmapInitialized = {
  airdrop: Address;
  bitmap: Address;
  bitmapId: number;
  timestamp: bigint;
};

export type BitmapInitializedArgs = {
  airdrop: Address;
  bitmap: Address;
  bitmapId: number;
  timestamp: number | bigint;
};

export function getBitmapInitializedEncoder(): FixedSizeEncoder<BitmapInitializedArgs> {
  return getStructEncoder([
    ["airdrop", getAddressEncoder()],
    ["bitmap", getAddressEncoder()],
    ["bitmapId", getU16Encoder()],
    ["timestamp", getI64Encoder()],
  ]);
}

export function getBitmapInitializedDecoder(): FixedSizeDecoder<BitmapInitialized> {
  return getStructDecoder([
    ["airdrop", getAddressDecoder()],
    ["bitmap", getAddressDecoder()],
    ["bitmapId", getU16Decoder()],
    ["timestamp", getI64Decoder()],
  ]);
}

export function getBitmapInitializedCodec(): FixedSizeCodec<
  BitmapInitializedArgs,
  BitmapInitialized
> {
  return combineCodec(
    getBitmapInitializedEncoder(),
    getBitmapInitializedDecoder(),
  );
}
