/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type TokensRedeemed = {
  airdrop: Address;
  authority: Address;
  timestamp: bigint;
};

export type TokensRedeemedArgs = {
  airdrop: Address;
  authority: Address;
  timestamp: number | bigint;
};

export function getTokensRedeemedEncoder(): FixedSizeEncoder<TokensRedeemedArgs> {
  return getStructEncoder([
    ["airdrop", getAddressEncoder()],
    ["authority", getAddressEncoder()],
    ["timestamp", getI64Encoder()],
  ]);
}

export function getTokensRedeemedDecoder(): FixedSizeDecoder<TokensRedeemed> {
  return getStructDecoder([
    ["airdrop", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["timestamp", getI64Decoder()],
  ]);
}

export function getTokensRedeemedCodec(): FixedSizeCodec<
  TokensRedeemedArgs,
  TokensRedeemed
> {
  return combineCodec(getTokensRedeemedEncoder(), getTokensRedeemedDecoder());
}
